server:
  port: 8585

spring:
  jackson:
    serialization:
      indent_output: true


management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
        timeout:
          enabled: false

feign:
  hystrix:
    enabled: true

  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000