version: "3"
services:

  eureka-service:
    image: afrunt/spring-cloud-imdb-eureka-service
    ports:
      - 8000:8000
    volumes:
      - ./config/eureka:/deployment/config

  ui:
    image: afrunt/spring-cloud-imdb-ui
    environment:
      - NGINX_PORT=8989

  api-gateway:
    image: afrunt/spring-cloud-imdb-api-gateway
    ports:
      - 80:7777
    volumes:
      - ./config/api-gateway:/deployment/config

  title-basics-service:
    image: afrunt/spring-cloud-imdb-title-basics-service
    volumes:
      - ./config/title-basics-service:/deployment/config
    depends_on:
      - eureka-service

  crawler-service:
    image: afrunt/spring-cloud-imdb-data-crawler
    volumes:
      - ./config/crawler-service:/deployment/config
    depends_on:
      - eureka-service
      - title-basics-service







