apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler-service
  template:
    metadata:
      labels:
        app: crawler-service
    spec:
      containers:
        - name: web
          image: afrunt/spring-cloud-imdb-data-crawler
          ports:
            - name: http
              containerPort: 8585
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 2
            httpGet:
              port: http
              path: /actuator/health
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 5
            httpGet:
              port: http
              path: /actuator/health
          volumeMounts:
            - name: "config"
              mountPath: "/deployment/config/bootstrap.yml"
              subPath: "bootstrap.yml"
      volumes:
        - name: "config"
          configMap:
            name: "crawler-service-cm"
