apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
          env:
            - name: "cluster.name"
              value: "elasticsearch"
            - name: "bootstrap.memory_lock"
              value: "false"
            - name: "ES_JAVA_OPTS"
              value: "-Xms512m -Xmx512m"
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          volumeMounts:
            - name: imdb-data
              mountPath: /usr/share/elasticsearch/data
              subPath: es/es1

      volumes:
        - name: "imdb-data"
          persistentVolumeClaim:
            claimName: imdb-pvc

