apiVersion: v1
kind: ConfigMap
metadata:
  name: es-cm
data:
  elasticsearch.yml: |
    cluster.name: elasticsearch
    network.host: "0.0.0.0"
    bootstrap.memory_lock: false
    discovery.zen.ping.unicast.hosts: elasticsearch
    discovery.zen.minimum_master_nodes: 1
    xpack.security.enabled: false
    xpack.monitoring.enabled: true
  ES_JAVA_OPTS: -Xms512m -Xmx512m
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-ss
spec:
  serviceName: elasticsearch
  replicas: 2
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
          env:
            - name: ES_JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: es-cm
                  key: ES_JAVA_OPTS
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /_cluster/health?local=true
              port: 9200
            initialDelaySeconds: 5

          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
              subPath: es/

            - name: elasticsearch-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml

      volumes:
        - name: elasticsearch-config
          configMap:
            name: es-cm
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml

  volumeClaimTemplates:
    - metadata:
        name: es-data
      spec:
        resources:
          requests:
            storage: 5Gi
        accessModes:
          - ReadWriteOnce