apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: afrunt/spring-cloud-imdb-web

          ports:
            - name: http
              containerPort: 8080

          readinessProbe:
            initialDelaySeconds: 30
            failureThreshold: 15
            timeoutSeconds: 5
            httpGet:
              port: http
              path: /actuator/health

          livenessProbe:
            initialDelaySeconds: 30
            failureThreshold: 15
            timeoutSeconds: 5
            httpGet:
              port: http
              path: /actuator/health

          volumeMounts:
            - name: "config"
              mountPath: "/deployment/config/bootstrap.yml"
              subPath: "bootstrap.yml"

      volumes:
        - name: "config"
          configMap:
            name: "web-cm"
